version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./.ha_config:/config
      - ./custom_components/scene_saver:/config/custom_components/scene_saver
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    ports:
      - "8123:8123"
    restart: unless-stopped
    privileged: true
